const constants = {
  CHANGE_USERNAME: 'CHANGE_USERNAME',
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  CHANGE_LOCATION: 'CHANGE_LOCATION',
  PRINT_SWEAR_WORD: 'PRINT_SWEAR_WORD',
  GET_EMAIL: 'GET_EMAIL',
  FULFILLED: '_FULFILLED'
}

export default constants